version: 0.0.5
name: dirt_arch
description: This package has the reference of many packages to facilitate the creation of apps without having to look for packages
author: Bwolf <bwolf@flutterando.com.br>
homepage: https://github.com/Bwolfs2/dirt_arch.git



environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <3.0.0"

dependencies:
  hasura_connect: ^2.0.0
  mask_text_input_formatter: ^1.1.0
  connectivity: ^2.0.2
  animated_card: ^1.0.0+8
  google_fonts: ^1.1.0
  flutter_modular: ^2.0.1
  bubble_bottom_bar: ^1.2.0
  meta: ^1.1.8
  convex_bottom_bar: ^2.4.1
  flutter_form_builder: ^3.14.1
  bot_toast: ^3.0.1
  dio: ^3.0.10
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
